# Site settings
title: "Franklin Shop Theme"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

shop:
  name: "Franklin Shop Theme"
  phone: "111 222 3333"
  email: "email@shop-name.com"
  customer_accounts_enabled: true
  customer_accounts_optional: true

# Exclude directories and/or files from the conversion.
exclude: []

# Collections
collections:
  collections:
    output: true
    permalink: /:collection/:path/
  products:
    output: true
    permalink: /:collection/:path/
